<?php
/*
This script is generated by scrape.py at 2012-04-21 10:29:25.
http://svn.coderepos.org/share/lang/python/cidr-mobilejp/trunk/scrape.py
*/
function ip2mobile($ip) {
  $n = sprintf('%u', ip2long($ip));

  if ($n < 1914014208) {
    if ($n < 1867942952) {
      if ($n < 998277120) {
        if ($n < 21905408) {
          if ($n < 21780480) {
            if ($n < 21495808) {
              if ($n >= 21127168 && $n <= 21129727) {
                return 'docomosp';
              }
            } else if ($n <= 21754879) {
              return 'docomosp';
            } else {
              if ($n >= 21757952 && $n <= 21778431) {
                return 'docomosp';
              }
            }
          } else if ($n <= 21811199) {
            return 'docomosp';
          } else {
            if ($n < 21846016) {
              if ($n >= 21813248 && $n <= 21843967) {
                return 'docomosp';
              }
            } else if ($n <= 21876735) {
              return 'docomosp';
            } else {
              if ($n < 21878784) {
              } else if ($n <= 21900287) {
                return 'docomosp';
              } else {
                if ($n >= 21905408 && $n <= 21913599) {
                  return 'docomosp';
                }
              }
            }
          }
        } else if ($n <= 21921791) {
          return 'docomosp';
        } else {
          if ($n < 21929984) {
            if ($n < 21921792) {
              if ($n >= 21913600 && $n <= 21915391) {
                return 'docomosp';
              }
            } else if ($n <= 21929983) {
              return 'docomosp';
            } else {
              if ($n >= 21921792 && $n <= 21938175) {
                return 'docomosp';
              }
            }
          } else if ($n <= 21932031) {
            return 'docomosp';
          } else {
            if ($n < 22003712) {
              if ($n >= 21938176 && $n <= 21999615) {
                return 'docomosp';
              }
            } else if ($n <= 22011903) {
              return 'docomosp';
            } else {
              if ($n < 828375040) {
              } else if ($n <= 828391423) {
                return 'docomosp';
              } else {
                if ($n >= 828507904 && $n <= 828510463) {
                  return 'docomosp';
                }
              }
            }
          }
        }
      } else if ($n <= 998281215) {
        return 'ezweb';
      } else {
        if ($n < 1036427264) {
          if ($n < 1036419072) {
            if ($n < 998713216) {
              if ($n >= 998712960 && $n <= 998713087) {
                return 'ezweb';
              }
            } else if ($n <= 998713247) {
              return 'ezweb';
            } else {
              if ($n >= 1031078432 && $n <= 1031078447) {
                return 'ezweb';
              }
            }
          } else if ($n <= 1036421631) {
            return 'airhphone';
          } else {
            if ($n < 1036421888) {
              if ($n >= 1036421732 && $n <= 1036421735) {
                return 'airhphone';
              }
            } else if ($n <= 1036421895) {
              return 'airhphone';
            } else {
              if ($n < 1036422016) {
              } else if ($n <= 1036422063) {
                return 'airhphone';
              } else {
                if ($n >= 1036422144 && $n <= 1036423167) {
                  return 'airhphone';
                }
              }
            }
          }
        } else if ($n <= 1036429055) {
          return 'airhphone';
        } else {
          if ($n < 1036779520) {
            if ($n < 1036449792) {
              if ($n >= 1036429312 && $n <= 1036431359) {
                return 'airhphone';
              }
            } else if ($n <= 1036451839) {
              return 'airhphone';
            } else {
              if ($n >= 1036451584 && $n <= 1036451839) {
                return 'airhphone';
              }
            }
          } else if ($n <= 1036779775) {
            return 'airhphone';
          } else {
            if ($n < 1036803072) {
              if ($n >= 1036780032 && $n <= 1036781439) {
                return 'airhphone';
              }
            } else if ($n <= 1036804095) {
              return 'airhphone';
            } else {
              if ($n < 1856177664) {
              } else if ($n <= 1856179711) {
                return 'docomosp';
              } else {
                if ($n >= 1856231424 && $n <= 1856234495) {
                  return 'docomosp';
                }
              }
            }
          }
        }
      }
    } else if ($n <= 1867942975) {
      return 'ezweb';
    } else {
      if ($n < 1913928448) {
        if ($n < 1913925888) {
          if ($n < 1867944704) {
            if ($n < 1867943552) {
              if ($n >= 1867943232 && $n <= 1867943487) {
                return 'ezweb';
              }
            } else if ($n <= 1867943743) {
              return 'ezweb';
            } else {
              if ($n >= 1867943872 && $n <= 1867943935) {
                return 'ezweb';
              }
            }
          } else if ($n <= 1867944959) {
            return 'ezweb';
          } else {
            if ($n < 1869313024) {
              if ($n >= 1868034432 && $n <= 1868034447) {
                return 'ezweb';
              }
            } else if ($n <= 1869313151) {
              return 'ezweb';
            } else {
              if ($n < 1869313216) {
              } else if ($n <= 1869313231) {
                return 'ezweb';
              } else {
                if ($n >= 1913925888 && $n <= 1913926143) {
                  return 'airhphone';
                }
              }
            }
          }
        } else if ($n <= 1913926399) {
          return 'airhphone';
        } else {
          if ($n < 1913927168) {
            if ($n < 1913926400) {
              if ($n >= 1913926144 && $n <= 1913926655) {
                return 'airhphone';
              }
            } else if ($n <= 1913926911) {
              return 'airhphone';
            } else {
              if ($n >= 1913926656 && $n <= 1913927423) {
                return 'airhphone';
              }
            }
          } else if ($n <= 1913927679) {
            return 'airhphone';
          } else {
            if ($n < 1913927680) {
              if ($n >= 1913927424 && $n <= 1913927935) {
                return 'airhphone';
              }
            } else if ($n <= 1913928191) {
              return 'airhphone';
            } else {
              if ($n < 1913927936) {
              } else if ($n <= 1913928447) {
                return 'airhphone';
              } else {
                if ($n >= 1913928192 && $n <= 1913928703) {
                  return 'airhphone';
                }
              }
            }
          }
        }
      } else if ($n <= 1913928959) {
        return 'airhphone';
      } else {
        if ($n < 1914011648) {
          if ($n < 1913929472) {
            if ($n < 1913928960) {
              if ($n >= 1913928704 && $n <= 1913929215) {
                return 'airhphone';
              }
            } else if ($n <= 1913929471) {
              return 'airhphone';
            } else {
              if ($n >= 1913929216 && $n <= 1913929727) {
                return 'airhphone';
              }
            }
          } else if ($n <= 1913929983) {
            return 'airhphone';
          } else {
            if ($n < 1913929984) {
              if ($n >= 1913929728 && $n <= 1913930239) {
                return 'airhphone';
              }
            } else if ($n <= 1913930495) {
              return 'airhphone';
            } else {
              if ($n < 1913930240) {
              } else if ($n <= 1913930751) {
                return 'airhphone';
              } else {
                if ($n >= 1913930496 && $n <= 1913930751) {
                  return 'airhphone';
                }
              }
            }
          }
        } else if ($n <= 1914011903) {
          return 'airhphone';
        } else {
          if ($n < 1914012928) {
            if ($n < 1914011904) {
              if ($n >= 1914011648 && $n <= 1914012159) {
                return 'airhphone';
              }
            } else if ($n <= 1914012415) {
              return 'airhphone';
            } else {
              if ($n < 1914012160) {
              } else if ($n <= 1914012927) {
                return 'airhphone';
              } else {
                if ($n >= 1914012672 && $n <= 1914013183) {
                  return 'airhphone';
                }
              }
            }
          } else if ($n <= 1914013439) {
            return 'airhphone';
          } else {
            if ($n < 1914013440) {
              if ($n >= 1914013184 && $n <= 1914013695) {
                return 'airhphone';
              }
            } else if ($n <= 1914013951) {
              return 'airhphone';
            } else {
              if ($n < 1914013696) {
              } else if ($n <= 1914014207) {
                return 'airhphone';
              } else {
                if ($n >= 1914013952 && $n <= 1914014463) {
                  return 'airhphone';
                }
              }
            }
          }
        }
      }
    }
  } else if ($n <= 1914014719) {
    return 'airhphone';
  } else {
    if ($n < 2098990592) {
      if ($n < 1989727872) {
        if ($n < 1914016512) {
          if ($n < 1914015232) {
            if ($n < 1914014720) {
              if ($n >= 1914014464 && $n <= 1914014975) {
                return 'airhphone';
              }
            } else if ($n <= 1914015231) {
              return 'airhphone';
            } else {
              if ($n >= 1914014976 && $n <= 1914015487) {
                return 'airhphone';
              }
            }
          } else if ($n <= 1914015743) {
            return 'airhphone';
          } else {
            if ($n < 1914015744) {
              if ($n >= 1914015488 && $n <= 1914015999) {
                return 'airhphone';
              }
            } else if ($n <= 1914016255) {
              return 'airhphone';
            } else {
              if ($n < 1914016000) {
              } else if ($n <= 1914016511) {
                return 'airhphone';
              } else {
                if ($n >= 1914016256 && $n <= 1914016767) {
                  return 'airhphone';
                }
              }
            }
          }
        } else if ($n <= 1914017023) {
          return 'airhphone';
        } else {
          if ($n < 1914044160) {
            if ($n < 1914017024) {
              if ($n >= 1914016768 && $n <= 1914017279) {
                return 'airhphone';
              }
            } else if ($n <= 1914017279) {
              return 'airhphone';
            } else {
              if ($n >= 1914043904 && $n <= 1914043935) {
                return 'airhphone';
              }
            }
          } else if ($n <= 1914044191) {
            return 'airhphone';
          } else {
            if ($n < 1966539104) {
              if ($n >= 1914044160 && $n <= 1914044191) {
                return 'airhphone';
              }
            } else if ($n <= 1966539199) {
              return 'emobile';
            } else {
              if ($n < 1966539232) {
              } else if ($n <= 1966539263) {
                return 'emobile';
              } else {
                if ($n >= 1966555392 && $n <= 1966555407) {
                  return 'emobile';
                }
              }
            }
          }
        }
      } else if ($n <= 1989727999) {
        return 'ezweb';
      } else {
        if ($n < 2070736240) {
          if ($n < 1990165952) {
            if ($n < 1990165664) {
              if ($n >= 1990165248 && $n <= 1990165375) {
                return 'ezweb';
              }
            } else if ($n <= 1990165695) {
              return 'ezweb';
            } else {
              if ($n >= 1990165760 && $n <= 1990165887) {
                return 'ezweb';
              }
            }
          } else if ($n <= 1990166015) {
            return 'ezweb';
          } else {
            if ($n < 2037375904) {
              if ($n >= 2037375744 && $n <= 2037375871) {
                return 'ezweb';
              }
            } else if ($n <= 2037375935) {
              return 'ezweb';
            } else {
              if ($n < 2037376768) {
              } else if ($n <= 2037376895) {
                return 'ezweb';
              } else {
                if ($n >= 2070736128 && $n <= 2070736159) {
                  return 'softbank';
                }
              }
            }
          }
        } else if ($n <= 2070736271) {
          return 'softbank';
        } else {
          if ($n < 2098988800) {
            if ($n < 2070736864) {
              if ($n >= 2070736352 && $n <= 2070736383) {
                return 'softbank';
              }
            } else if ($n <= 2070736895) {
              return 'softbank';
            } else {
              if ($n < 2098987008) {
              } else if ($n <= 2098988799) {
                return 'airhphone';
              } else {
                if ($n >= 2098988544 && $n <= 2098989055) {
                  return 'airhphone';
                }
              }
            }
          } else if ($n <= 2098989311) {
            return 'airhphone';
          } else {
            if ($n < 2098989824) {
              if ($n >= 2098989824 && $n <= 2098990079) {
                return 'airhphone';
              }
            } else if ($n <= 2098990335) {
              return 'airhphone';
            } else {
              if ($n < 2098990080) {
              } else if ($n <= 2098990591) {
                return 'airhphone';
              } else {
                if ($n >= 2098990336 && $n <= 2098990847) {
                  return 'airhphone';
                }
              }
            }
          }
        }
      }
    } else if ($n <= 2098991615) {
      return 'airhphone';
    } else {
      if ($n < 3541233152) {
        if ($n < 3532785600) {
          if ($n < 3405602960) {
            if ($n < 3075129344) {
              if ($n >= 3075080192 && $n <= 3075082751) {
                return 'docomosp';
              }
            } else if ($n <= 3075131903) {
              return 'docomosp';
            } else {
              if ($n >= 3405602816 && $n <= 3405602847) {
                return 'softbank';
              }
            }
          } else if ($n <= 3405602991) {
            return 'softbank';
          } else {
            if ($n < 3405603728) {
              if ($n >= 3405603040 && $n <= 3405603071) {
                return 'softbank';
              }
            } else if ($n <= 3405603759) {
              return 'softbank';
            } else {
              if ($n < 3414864896) {
              } else if ($n <= 3414865407) {
                return 'docomosp';
              } else {
                if ($n >= 3414870784 && $n <= 3414871039) {
                  return 'docomosp';
                }
              }
            }
          }
        } else if ($n <= 3532785663) {
          return 'softbank';
        } else {
          if ($n < 3538206148) {
            if ($n < 3534314496) {
              if ($n >= 3534288384 && $n <= 3534288895) {
                return 'airhphone';
              }
            } else if ($n <= 3534316543) {
              return 'airhphone';
            } else {
              if ($n >= 3538206140 && $n <= 3538206143) {
                return 'softbank';
              }
            }
          } else if ($n <= 3538206151) {
            return 'softbank';
          } else {
            if ($n < 3539975680) {
              if ($n >= 3538321632 && $n <= 3538321647) {
                return 'ezweb';
              }
            } else if ($n <= 3539975935) {
              return 'airhphone';
            } else {
              if ($n < 3539975680) {
              } else if ($n <= 3539975935) {
                return 'airhphone';
              } else {
                if ($n >= 3541231616 && $n <= 3541233407) {
                  return 'airhphone';
                }
              }
            }
          }
        }
      } else if ($n <= 3541233663) {
        return 'airhphone';
      } else {
        if ($n < 3681328384) {
          if ($n < 3681288704) {
            if ($n < 3548299392) {
              if ($n >= 3541233408 && $n <= 3541233663) {
                return 'airhphone';
              }
            } else if ($n <= 3548299519) {
              return 'airhphone';
            } else {
              if ($n >= 3681288704 && $n <= 3681288959) {
                return 'airhphone';
              }
            }
          } else if ($n <= 3681289215) {
            return 'airhphone';
          } else {
            if ($n < 3681289216) {
              if ($n >= 3681288960 && $n <= 3681289471) {
                return 'airhphone';
              }
            } else if ($n <= 3681289727) {
              return 'airhphone';
            } else {
              if ($n < 3681289472) {
              } else if ($n <= 3681289983) {
                return 'airhphone';
              } else {
                if ($n >= 3681289728 && $n <= 3681292287) {
                  return 'airhphone';
                }
              }
            }
          }
        } else if ($n <= 3681328511) {
          return 'ezweb';
        } else {
          if ($n < 3715563520) {
            if ($n < 3681328680) {
              if ($n >= 3681328640 && $n <= 3681328671) {
                return 'ezweb';
              }
            } else if ($n <= 3681328687) {
              return 'ezweb';
            } else {
              if ($n < 3682439424) {
              } else if ($n <= 3682439551) {
                return 'ezweb';
              } else {
                if ($n >= 3682439680 && $n <= 3682439695) {
                  return 'ezweb';
                }
              }
            }
          } else if ($n <= 3715565055) {
            return 'airhphone';
          } else {
            if ($n < 3724642368) {
              if ($n >= 3715564800 && $n <= 3715566079) {
                return 'airhphone';
              }
            } else if ($n <= 3724642431) {
              return 'ezweb';
            } else {
              if ($n < 3724885632) {
              } else if ($n <= 3724885759) {
                return 'ezweb';
              } else {
                if ($n >= 3725542592 && $n <= 3725542655) {
                  return 'ezweb';
                }
              }
            }
          }
        }
      }
    }
  }
  return 'pc';
}
?>

